// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HomePage": {
    "hero": {
      "title": "地域と未来を照らす、\n電気と技術のプロフェッショナル集団",
      "description": "オフィス・工場・施設の電気工事から、防犯・通信インフラまで。\n関東エリアを中心に、安全・確実な施工を提供しています。",
      "cta": {
        "consultation": "ご相談・お見積りはこちら",
        "careers": "採用情報を見る",
        "works": "施工実績を見る"
      }
    },
    "services": {
      "title": "対応工事・サービス一覧",
      "items": {
        "electrical": {
          "title": "一般電気工事",
          "description": "分電盤・照明・コンセントなど、建物の基本設備を支える確かな施工"
        },
        "security": {
          "title": "防犯設備工事",
          "description": "ITVカメラ・入退室管理システムなど、防犯・監視の強化をサポート"
        },
        "network": {
          "title": "LAN・ネットワーク工事",
          "description": "オフィスや施設の快適な通信環境を整備。無線LAN・電話配線も対応"
        },
        "fiber": {
          "title": "光ケーブル融着・測定工事",
          "description": "高速通信の基盤をつなぐ光ファイバー工事、融着・測定まで一貫対応"
        }
      },
      "cta": "サービス詳細を見る"
    },
    "works": {
      "title": "これまでの施工実績",
      "description": "工場・オフィス・店舗など、幅広い現場で積み重ねた経験と信頼。施工前後のビフォー・アフターもぜひご覧ください。",
      "cta": "すべての実績を見る"
    },
    "recruit": {
      "title": "未経験から、一緒に成長できる仲間を募集しています！",
      "description": "資格取得支援・研修制度あり。手に職をつけたい方、ぜひ一度お話しませんか？",
      "cta": "採用情報を見る"
    },
    "news": {
      "title": "最新ニュース・お知らせ",
      "description": "会社の活動報告・施工レポート・採用に関する最新情報を発信中です。",
      "cta": "もっと見る"
    },
    "strengths": {
      "title": "ウィルネットが選ばれる理由",
      "description": "有資格者多数・創業○年の実績・柔軟なワンストップ対応。関東エリアの多様な現場に応える技術と経験があります。",
      "items": {
        "technology": {
          "title": "確かな技術力",
          "description": "有資格者による施工・丁寧な対応"
        },
        "flexibility": {
          "title": "柔軟な対応力",
          "description": "法人・個人問わず、現場に最適解を提案"
        },
        "experience": {
          "title": "安心の実績",
          "description": "多様な現場・工事経験"
        }
      }
    },
    "contact": {
      "title": "お気軽にお問い合わせください",
      "description": "工事のご相談・お見積り・採用に関するお問い合わせは、下記フォームまたはお電話でどうぞ。",
      "cta": "お問い合わせフォームへ"
    }
  },
  "ServicesPage": {
    "hero": {
      "title": "ウィルネットの事業内容",
      "description": "電気・通信・防犯の全領域で、確かな技術とスピードをお届けします。"
    },
    "services": {
      "electrical": {
        "title": "一般電気工事",
        "catch": "目に見えない安心を、配線の中に。",
        "description": "分電盤・照明・コンセントの設置・改修、非常用電源工事、住宅・オフィス・工場の電気施工まで、安心の技術でサポートいたします。"
      },
      "security": {
        "title": "防犯設備・ITVカメラ工事",
        "catch": "守る技術で、現場に安心を。",
        "description": "防犯カメラ設置・設定、入退室管理（ICカード・生体認証）、セキュリティセンサー・警報装置など、建物の安全を守るための設備を提案・施工いたします。"
      },
      "network": {
        "title": "LAN配線・ネットワーク工事",
        "catch": "止まらないネットワークで業務効率を最大化。",
        "description": "LAN配線（有線・無線）、Wi-Fiアクセスポイント設置、ルータ・HUB設定、ネットワーク機器導入など、オフィスのITインフラを支えます。"
      },
      "fiber": {
        "title": "光ケーブル配線・融着測定",
        "catch": "高速通信の基盤を、緻密な作業で支える。",
        "description": "光ファイバー敷設、融着接続作業・OTDR測定、通信業者・企業向けネットワーク施工など、専門技術者による高精度な対応を行います。"
      }
    },
    "strengths": {
      "title": "ウィルネットの強み",
      "description": "サービスに共通する強みをピックアップしました。",
      "items": {
        "qualification": {
          "title": "資格保有者多数",
          "description": "国家資格者が対応いたします。"
        },
        "onestop": {
          "title": "ワンストップ対応",
          "description": "設計から施工、保守まで一貫体制でサポート。"
        },
        "local": {
          "title": "地域密着型",
          "description": "千葉・関東エリアでの豊富な実績。"
        }
      }
    },
    "area": {
      "title": "対応エリア",
      "description": "千葉県を中心に、関東エリア全域に対応いたします。"
    }
  },
  "NewsPage": {
    "title": "ニュース一覧"
  },
  "NewsDetailPage": {
    "title": "ニュース詳細"
  },
  "LocaleLayout": {
    "title": "next-intl Beispiel"
  },
  "WorksPage": {
    "title": "施工実績一覧",
    "catch": "確かな技術と信頼で、お客様の現場を支えます。",
    "filters": {
      "category": "カテゴリー",
      "area": "エリア",
      "all": "すべて"
    },
    "viewDetails": "詳細を見る"
  },
  "WorkDetail": {
    "basicInfo": "基本情報",
    "period": "施工期間",
    "area": "施工エリア",
    "category": "カテゴリー",
    "techPoint": "技術ポイント",
    "description": "詳細説明",
    "gallery": "関連写真",
    "backToList": "一覧に戻る"
  },
  "ContactCTA": {
    "title": "お気軽にご相談ください",
    "description": "工事のご相談・お見積り・採用に関するお問い合わせは、下記フォームまたはお電話でどうぞ。",
    "cta": "お問い合わせフォームへ"
  }
};
export default messages;